#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AICampBP

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function AICampBP.AICampBP_C.ExecuteUbergraph_AICampBP
// 0x0004 (0x0004 - 0x0000)
struct AICampBP_C_ExecuteUbergraph_AICampBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_AICampBP_C_ExecuteUbergraph_AICampBP;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
