#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_D_8

#include "Basic.hpp"

#include "B_D_8_classes.hpp"
#include "B_D_8_parameters.hpp"


SDK_NAMESPACE_START

// Function B_D_8.B_D_8_C.ExecuteUbergraph_B_D_8
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_D_8_C::ExecuteUbergraph_B_D_8(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_D_8_C", "ExecuteUbergraph_B_D_8");

	Params::B_D_8_C_ExecuteUbergraph_B_D_8 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_D_8.B_D_8_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_D_8_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_D_8_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_D_8.B_D_8_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_D_8_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_D_8_C", "ReceiveTick");

	Params::B_D_8_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_D_8.B_D_8_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AB_D_8_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_D_8_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
