#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePass_EpicQuestReward

#include "Basic.hpp"

#include "BattlePass_EpicQuestReward_classes.hpp"
#include "BattlePass_EpicQuestReward_parameters.hpp"


SDK_NAMESPACE_START

// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.Is unselected
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePass_EpicQuestReward_C::Is_unselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "Is unselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.Is Selected
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePass_EpicQuestReward_C::Is_Selected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "Is Selected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.Initialize epic quest reward
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UEpicQuest_Header_C*              Parent                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Complete                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_EpicQuestReward_C::Initialize_epic_quest_reward(class UEpicQuest_Header_C* Parent, bool Complete)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "Initialize epic quest reward");

	Params::BattlePass_EpicQuestReward_C_Initialize_epic_quest_reward Parms{};

	Parms.Parent = Parent;
	Parms.Complete = Complete;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_EpicQuestReward_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "Tick");

	Params::BattlePass_EpicQuestReward_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.BndEvt__Button_Option_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBattlePass_EpicQuestReward_C::BndEvt__Button_Option_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "BndEvt__Button_Option_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.BndEvt__Button_Option_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBattlePass_EpicQuestReward_C::BndEvt__Button_Option_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "BndEvt__Button_Option_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_EpicQuestReward.BattlePass_EpicQuestReward_C.ExecuteUbergraph_BattlePass_EpicQuestReward
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_EpicQuestReward_C::ExecuteUbergraph_BattlePass_EpicQuestReward(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_EpicQuestReward_C", "ExecuteUbergraph_BattlePass_EpicQuestReward");

	Params::BattlePass_EpicQuestReward_C_ExecuteUbergraph_BattlePass_EpicQuestReward Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
