#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CaptainDarwinLootBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CaptainDarwinLootBP.CaptainDarwinLootBP_C
// 0x0020 (0x0400 - 0x03E0)
class ACaptainDarwinLootBP_C final : public ADarwinLoot
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x03F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void EventLootPickedUp(class ADarwinCharacter* Character);
	void EventLootReset();
	void ExecuteUbergraph_CaptainDarwinLootBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CaptainDarwinLootBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CaptainDarwinLootBP_C")
	}
	static class ACaptainDarwinLootBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACaptainDarwinLootBP_C>();
	}
};
DUMPER7_ASSERTS_ACaptainDarwinLootBP_C;

SDK_NAMESPACE_END
