#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomMatch_enterInvitation

#include "Basic.hpp"

#include "CustomMatch_enterInvitation_classes.hpp"
#include "CustomMatch_enterInvitation_parameters.hpp"


SDK_NAMESPACE_START

// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.BndEvt__CodeBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCustomMatch_enterInvitation_C::BndEvt__CodeBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "BndEvt__CodeBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::CustomMatch_enterInvitation_C_BndEvt__CodeBox_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.BndEvt__CodeBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UCustomMatch_enterInvitation_C::BndEvt__CodeBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "BndEvt__CodeBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::CustomMatch_enterInvitation_C_BndEvt__CodeBox_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.BndEvt__NavButton_Password_Back_K2Node_ComponentBoundEvent_6_On Clicked__DelegateSignature
// (BlueprintEvent)

void UCustomMatch_enterInvitation_C::BndEvt__NavButton_Password_Back_K2Node_ComponentBoundEvent_6_On_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "BndEvt__NavButton_Password_Back_K2Node_ComponentBoundEvent_6_On Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.BndEvt__NavButton_Password_Join_K2Node_ComponentBoundEvent_3_On Clicked__DelegateSignature
// (BlueprintEvent)

void UCustomMatch_enterInvitation_C::BndEvt__NavButton_Password_Join_K2Node_ComponentBoundEvent_3_On_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "BndEvt__NavButton_Password_Join_K2Node_ComponentBoundEvent_3_On Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.EventFriendPartyJoined
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      FriendName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UCustomMatch_enterInvitation_C::EventFriendPartyJoined(const class FText& FriendName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "EventFriendPartyJoined");

	Params::CustomMatch_enterInvitation_C_EventFriendPartyJoined Parms{};

	Parms.FriendName = std::move(FriendName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.EventInputSourceChanged
// (Event, Public, BlueprintEvent)

void UCustomMatch_enterInvitation_C::EventInputSourceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "EventInputSourceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.EventMenuXPressed
// (Event, Public, BlueprintEvent)

void UCustomMatch_enterInvitation_C::EventMenuXPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "EventMenuXPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.ExecuteUbergraph_CustomMatch_enterInvitation
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCustomMatch_enterInvitation_C::ExecuteUbergraph_CustomMatch_enterInvitation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "ExecuteUbergraph_CustomMatch_enterInvitation");

	Params::CustomMatch_enterInvitation_C_ExecuteUbergraph_CustomMatch_enterInvitation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.Hide Invitation Pop Up
// (BlueprintCallable, BlueprintEvent)

void UCustomMatch_enterInvitation_C::Hide_Invitation_Pop_Up()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "Hide Invitation Pop Up");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.Join by enter
// (BlueprintCallable, BlueprintEvent)

void UCustomMatch_enterInvitation_C::Join_by_enter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "Join by enter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.OnJoinWithInvitation
// (BlueprintCallable, BlueprintEvent)

void UCustomMatch_enterInvitation_C::OnJoinWithInvitation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "OnJoinWithInvitation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.Open Invitation Pop Up
// (BlueprintCallable, BlueprintEvent)

void UCustomMatch_enterInvitation_C::Open_Invitation_Pop_Up()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "Open Invitation Pop Up");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.RefreshVisibilities
// (Public, BlueprintCallable, BlueprintEvent)

void UCustomMatch_enterInvitation_C::RefreshVisibilities()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "RefreshVisibilities");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.ResetState
// (BlueprintCallable, BlueprintEvent)

void UCustomMatch_enterInvitation_C::ResetState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "ResetState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.WidgetAnimationEvt_CloseInvitationPopUp_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UCustomMatch_enterInvitation_C::WidgetAnimationEvt_CloseInvitationPopUp_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "WidgetAnimationEvt_CloseInvitationPopUp_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CustomMatch_enterInvitation.CustomMatch_enterInvitation_C.WidgetAnimationEvt_OpenInvitationPopUp_K2Node_WidgetAnimationEvent_1
// (BlueprintEvent)

void UCustomMatch_enterInvitation_C::WidgetAnimationEvt_OpenInvitationPopUp_K2Node_WidgetAnimationEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomMatch_enterInvitation_C", "WidgetAnimationEvt_OpenInvitationPopUp_K2Node_WidgetAnimationEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
