#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DarwinGameStateBP

#include "Basic.hpp"

#include "DarwinGameStateBP_classes.hpp"
#include "DarwinGameStateBP_parameters.hpp"


SDK_NAMESPACE_START

// Function DarwinGameStateBP.DarwinGameStateBP_C.CheckChampionChooserBlocked
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADarwinGameStateBP_C::CheckChampionChooserBlocked(bool* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinGameStateBP_C", "CheckChampionChooserBlocked");

	Params::DarwinGameStateBP_C_CheckChampionChooserBlocked Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function DarwinGameStateBP.DarwinGameStateBP_C.EventExecutePower
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Loc                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bAutoVote                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADarwinGameStateBP_C::EventExecutePower(class AActor* TargetActor, const struct FVector& Loc, EDarwinItemTypeEnum PowerType, bool bAutoVote)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinGameStateBP_C", "EventExecutePower");

	Params::DarwinGameStateBP_C_EventExecutePower Parms{};

	Parms.TargetActor = TargetActor;
	Parms.Loc = std::move(Loc);
	Parms.PowerType = PowerType;
	Parms.bAutoVote = bAutoVote;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DarwinGameStateBP.DarwinGameStateBP_C.EventTeleportedAtStartPosition
// (Event, Public, BlueprintEvent)

void ADarwinGameStateBP_C::EventTeleportedAtStartPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinGameStateBP_C", "EventTeleportedAtStartPosition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DarwinGameStateBP.DarwinGameStateBP_C.ExecuteUbergraph_DarwinGameStateBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADarwinGameStateBP_C::ExecuteUbergraph_DarwinGameStateBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinGameStateBP_C", "ExecuteUbergraph_DarwinGameStateBP");

	Params::DarwinGameStateBP_C_ExecuteUbergraph_DarwinGameStateBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
