#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EnvironmentTractionGrenadeBP

#include "Basic.hpp"

#include "EnvironmentTractionGrenadeBP_classes.hpp"
#include "EnvironmentTractionGrenadeBP_parameters.hpp"


SDK_NAMESPACE_START

// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EndGrappleFromDestro
// (BlueprintCallable, BlueprintEvent)

void AEnvironmentTractionGrenadeBP_C::EndGrappleFromDestro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EndGrappleFromDestro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EventEndGrapple
// (Event, Public, BlueprintEvent)

void AEnvironmentTractionGrenadeBP_C::EventEndGrapple()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EventEndGrapple");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EventGrenadeExplode
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   Loc                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   norm                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           impactActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AEnvironmentTractionGrenadeBP_C::EventGrenadeExplode(const struct FVector& Loc, const struct FVector& norm, class AActor* impactActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EventGrenadeExplode");

	Params::EnvironmentTractionGrenadeBP_C_EventGrenadeExplode Parms{};

	Parms.Loc = std::move(Loc);
	Parms.norm = std::move(norm);
	Parms.impactActor = impactActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EventHasSetCharacterOwner
// (Event, Public, BlueprintEvent)

void AEnvironmentTractionGrenadeBP_C::EventHasSetCharacterOwner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EventHasSetCharacterOwner");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EventHideAll
// (Event, Public, BlueprintEvent)

void AEnvironmentTractionGrenadeBP_C::EventHideAll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EventHideAll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EventHitByAxe
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   Loc                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEnvironmentTractionGrenadeBP_C::EventHitByAxe(const struct FVector& Loc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EventHitByAxe");

	Params::EnvironmentTractionGrenadeBP_C_EventHitByAxe Parms{};

	Parms.Loc = std::move(Loc);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.EventReflectedByForcefield
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   Loc                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEnvironmentTractionGrenadeBP_C::EventReflectedByForcefield(const struct FVector& Loc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "EventReflectedByForcefield");

	Params::EnvironmentTractionGrenadeBP_C_EventReflectedByForcefield Parms{};

	Parms.Loc = std::move(Loc);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.ExecuteUbergraph_EnvironmentTractionGrenadeBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEnvironmentTractionGrenadeBP_C::ExecuteUbergraph_EnvironmentTractionGrenadeBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "ExecuteUbergraph_EnvironmentTractionGrenadeBP");

	Params::EnvironmentTractionGrenadeBP_C_ExecuteUbergraph_EnvironmentTractionGrenadeBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void AEnvironmentTractionGrenadeBP_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEnvironmentTractionGrenadeBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "ReceiveTick");

	Params::EnvironmentTractionGrenadeBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EnvironmentTractionGrenadeBP.EnvironmentTractionGrenadeBP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AEnvironmentTractionGrenadeBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EnvironmentTractionGrenadeBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
