#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FuelComponentBP

#include "Basic.hpp"

#include "FuelComponentBP_classes.hpp"
#include "FuelComponentBP_parameters.hpp"


SDK_NAMESPACE_START

// Function FuelComponentBP.FuelComponentBP_C.EventOverheatEnd
// (Event, Public, BlueprintEvent)

void UFuelComponentBP_C::EventOverheatEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FuelComponentBP_C", "EventOverheatEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FuelComponentBP.FuelComponentBP_C.EventOverheatStart
// (Event, Public, BlueprintEvent)

void UFuelComponentBP_C::EventOverheatStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FuelComponentBP_C", "EventOverheatStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FuelComponentBP.FuelComponentBP_C.ExecuteUbergraph_FuelComponentBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFuelComponentBP_C::ExecuteUbergraph_FuelComponentBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FuelComponentBP_C", "ExecuteUbergraph_FuelComponentBP");

	Params::FuelComponentBP_C_ExecuteUbergraph_FuelComponentBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
