#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbyDroneBP

#include "Basic.hpp"

#include "LobbyDroneBP_classes.hpp"
#include "LobbyDroneBP_parameters.hpp"


SDK_NAMESPACE_START

// Function LobbyDroneBP.LobbyDroneBP_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   drone_type                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::CustomEvent(int32 drone_type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "CustomEvent");

	Params::LobbyDroneBP_C_CustomEvent Parms{};

	Parms.drone_type = drone_type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.EventHitted
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   hit_direction                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   hitLoc                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::EventHitted(const struct FVector& hit_direction, const struct FVector& hitLoc)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "EventHitted");

	Params::LobbyDroneBP_C_EventHitted Parms{};

	Parms.hit_direction = std::move(hit_direction);
	Parms.hitLoc = std::move(hitLoc);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.EventKillTrail
// (Event, Public, BlueprintEvent)

void ALobbyDroneBP_C::EventKillTrail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "EventKillTrail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LobbyDroneBP.LobbyDroneBP_C.EventSpawnTrail
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   drone_type                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::EventSpawnTrail(int32 drone_type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "EventSpawnTrail");

	Params::LobbyDroneBP_C_EventSpawnTrail Parms{};

	Parms.drone_type = drone_type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.EventUpdateDroneMaterial
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   MaterialIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::EventUpdateDroneMaterial(int32 MaterialIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "EventUpdateDroneMaterial");

	Params::LobbyDroneBP_C_EventUpdateDroneMaterial Parms{};

	Parms.MaterialIndex = MaterialIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.EventUpdateDroneRelativeLocation
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::EventUpdateDroneRelativeLocation(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "EventUpdateDroneRelativeLocation");

	Params::LobbyDroneBP_C_EventUpdateDroneRelativeLocation Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.EventUpdateDroneRelativeRotation
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FRotator&                  Rotation                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)

void ALobbyDroneBP_C::EventUpdateDroneRelativeRotation(const struct FRotator& Rotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "EventUpdateDroneRelativeRotation");

	Params::LobbyDroneBP_C_EventUpdateDroneRelativeRotation Parms{};

	Parms.Rotation = std::move(Rotation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.ExecuteUbergraph_LobbyDroneBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::ExecuteUbergraph_LobbyDroneBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "ExecuteUbergraph_LobbyDroneBP");

	Params::LobbyDroneBP_C_ExecuteUbergraph_LobbyDroneBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.Explosion
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Direction                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Intensity                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::Explosion(const struct FVector& Direction, double Intensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "Explosion");

	Params::LobbyDroneBP_C_Explosion Parms{};

	Parms.Direction = std::move(Direction);
	Parms.Intensity = Intensity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.GetDroneTransform
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransform*                      Transform                                              (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::GetDroneTransform(struct FTransform* Transform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "GetDroneTransform");

	Params::LobbyDroneBP_C_GetDroneTransform Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Transform != nullptr)
		*Transform = std::move(Parms.Transform);
}


// Function LobbyDroneBP.LobbyDroneBP_C.GetRandFloatInRange
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  min_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  max_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Random                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::GetRandFloatInRange(double min_0, double max_0, double* Random)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "GetRandFloatInRange");

	Params::LobbyDroneBP_C_GetRandFloatInRange Parms{};

	Parms.min_0 = min_0;
	Parms.max_0 = max_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Random != nullptr)
		*Random = Parms.Random;
}


// Function LobbyDroneBP.LobbyDroneBP_C.GetRandIntInRange
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   min_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   max_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  int_0                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::GetRandIntInRange(int32 min_0, int32 max_0, int32* int_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "GetRandIntInRange");

	Params::LobbyDroneBP_C_GetRandIntInRange Parms{};

	Parms.min_0 = min_0;
	Parms.max_0 = max_0;

	UObject::ProcessEvent(Func, &Parms);

	if (int_0 != nullptr)
		*int_0 = Parms.int_0;
}


// Function LobbyDroneBP.LobbyDroneBP_C.GetRandRotator
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FRotator*                        Rotator                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ALobbyDroneBP_C::GetRandRotator(struct FRotator* Rotator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "GetRandRotator");

	Params::LobbyDroneBP_C_GetRandRotator Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Rotator != nullptr)
		*Rotator = std::move(Parms.Rotator);
}


// Function LobbyDroneBP.LobbyDroneBP_C.InitFromBPValues
// (Public, BlueprintCallable, BlueprintEvent)

void ALobbyDroneBP_C::InitFromBPValues()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "InitFromBPValues");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LobbyDroneBP.LobbyDroneBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALobbyDroneBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LobbyDroneBP.LobbyDroneBP_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ALobbyDroneBP_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LobbyDroneBP.LobbyDroneBP_C.ReceiveHit
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              MyComp                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Other                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    bSelfMoved                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   HitNormal                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit_0                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ALobbyDroneBP_C::ReceiveHit(class UPrimitiveComponent* MyComp, class AActor* Other, class UPrimitiveComponent* OtherComp, bool bSelfMoved, const struct FVector& HitLocation, const struct FVector& HitNormal, const struct FVector& NormalImpulse, const struct FHitResult& Hit_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "ReceiveHit");

	Params::LobbyDroneBP_C_ReceiveHit Parms{};

	Parms.MyComp = MyComp;
	Parms.Other = Other;
	Parms.OtherComp = OtherComp;
	Parms.bSelfMoved = bSelfMoved;
	Parms.HitLocation = std::move(HitLocation);
	Parms.HitNormal = std::move(HitNormal);
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit_0 = std::move(Hit_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALobbyDroneBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "ReceiveTick");

	Params::LobbyDroneBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LobbyDroneBP.LobbyDroneBP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ALobbyDroneBP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LobbyDroneBP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
