#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MatchMakingWidget

#include "Basic.hpp"

#include "MatchMakingWidget_classes.hpp"
#include "MatchMakingWidget_parameters.hpp"


SDK_NAMESPACE_START

// Function MatchMakingWidget.MatchMakingWidget_C.BackOnSearchFailedAction
// (BlueprintCallable, BlueprintEvent)

void UMatchMakingWidget_C::BackOnSearchFailedAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "BackOnSearchFailedAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.BndEvt__CancelBtn_K2Node_ComponentBoundEvent_290_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMatchMakingWidget_C::BndEvt__CancelBtn_K2Node_ComponentBoundEvent_290_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "BndEvt__CancelBtn_K2Node_ComponentBoundEvent_290_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.BndEvt__NavButton_Color_K2Node_ComponentBoundEvent_0_On Clicked__DelegateSignature
// (BlueprintEvent)

void UMatchMakingWidget_C::BndEvt__NavButton_Color_K2Node_ComponentBoundEvent_0_On_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "BndEvt__NavButton_Color_K2Node_ComponentBoundEvent_0_On Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMatchMakingWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventInputSourceChanged
// (Event, Public, BlueprintEvent)

void UMatchMakingWidget_C::EventInputSourceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventInputSourceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMatchmakingCompleted
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FDarwinMatchmakingInfo&    matchmakingInfo                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UMatchMakingWidget_C::EventMatchmakingCompleted(const struct FDarwinMatchmakingInfo& matchmakingInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMatchmakingCompleted");

	Params::MatchMakingWidget_C_EventMatchmakingCompleted Parms{};

	Parms.matchmakingInfo = std::move(matchmakingInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMatchmakingRegionUpdated
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      RegionName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UMatchMakingWidget_C::EventMatchmakingRegionUpdated(const class FText& RegionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMatchmakingRegionUpdated");

	Params::MatchMakingWidget_C_EventMatchmakingRegionUpdated Parms{};

	Parms.RegionName = std::move(RegionName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMatchmakingServersFull
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FDarwinMatchmakingInfo&    matchmakingInfo                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UMatchMakingWidget_C::EventMatchmakingServersFull(const struct FDarwinMatchmakingInfo& matchmakingInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMatchmakingServersFull");

	Params::MatchMakingWidget_C_EventMatchmakingServersFull Parms{};

	Parms.matchmakingInfo = std::move(matchmakingInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMatchmakingStarted
// (Event, Public, BlueprintEvent)

void UMatchMakingWidget_C::EventMatchmakingStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMatchmakingStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMatchmakingUpdated
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// EDarwinRoleEnum                         Role                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FDarwinMatchmakingInfo&    matchmakingInfo                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UMatchMakingWidget_C::EventMatchmakingUpdated(EDarwinRoleEnum Role, const struct FDarwinMatchmakingInfo& matchmakingInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMatchmakingUpdated");

	Params::MatchMakingWidget_C_EventMatchmakingUpdated Parms{};

	Parms.Role = Role;
	Parms.matchmakingInfo = std::move(matchmakingInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMenuBack
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsEscape                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMatchMakingWidget_C::EventMenuBack(bool bIsEscape)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMenuBack");

	Params::MatchMakingWidget_C_EventMenuBack Parms{};

	Parms.bIsEscape = bIsEscape;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.EventMenuSpecialLeftPressed
// (Event, Public, BlueprintEvent)

void UMatchMakingWidget_C::EventMenuSpecialLeftPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "EventMenuSpecialLeftPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.ExecuteUbergraph_MatchMakingWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMatchMakingWidget_C::ExecuteUbergraph_MatchMakingWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "ExecuteUbergraph_MatchMakingWidget");

	Params::MatchMakingWidget_C_ExecuteUbergraph_MatchMakingWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.HideMatchmakingFailed
// (BlueprintCallable, BlueprintEvent)

void UMatchMakingWidget_C::HideMatchmakingFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "HideMatchmakingFailed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.Init Parent in Matchmaking
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMainMenu_C*                      MainMenu_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UHomeMenu_C*                      HomeMenu_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UMatchMakingWidget_C::Init_Parent_in_Matchmaking(class UMainMenu_C* MainMenu_0, class UHomeMenu_C* HomeMenu_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "Init Parent in Matchmaking");

	Params::MatchMakingWidget_C_Init_Parent_in_Matchmaking Parms{};

	Parms.MainMenu_0 = MainMenu_0;
	Parms.HomeMenu_0 = HomeMenu_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.IsMatchmakingWidgetDisplayed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsVisible_0                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMatchMakingWidget_C::IsMatchmakingWidgetDisplayed(bool* IsVisible_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "IsMatchmakingWidgetDisplayed");

	Params::MatchMakingWidget_C_IsMatchmakingWidgetDisplayed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsVisible_0 != nullptr)
		*IsVisible_0 = Parms.IsVisible_0;
}


// Function MatchMakingWidget.MatchMakingWidget_C.OnMatchmakingCancelAction
// (BlueprintCallable, BlueprintEvent)

void UMatchMakingWidget_C::OnMatchmakingCancelAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "OnMatchmakingCancelAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MatchMakingWidget.MatchMakingWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMatchMakingWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "Tick");

	Params::MatchMakingWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MatchMakingWidget.MatchMakingWidget_C.UpdateNavButtons
// (BlueprintCallable, BlueprintEvent)

void UMatchMakingWidget_C::UpdateNavButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MatchMakingWidget_C", "UpdateNavButtons");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
