#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MiniMapCharacterIconPylons

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass MiniMapCharacterIconPylons.MiniMapCharacterIconPylons_C
// 0x0068 (0x0F10 - 0x0EA8)
class UMiniMapCharacterIconPylons_C final : public UDarwinCharacterWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0EA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               Map;                                               // 0x0EB0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_25;                                          // 0x0EB8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<class ADarwinAICamp*, class UDarwinAICampMinimapIcon_C*> AICampToIcon;                      // 0x0EC0(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, ContainsInstancedReference)

public:
	void EventAICampActivated(class ADarwinAICamp* camp, bool bActivated, const struct FVector2D& Loc, const struct FVector& worldLoc);
	void EventGameHasStarted();
	void EventGameStartsNow();
	void EventPylonCreated(int32 Index_0, const struct FVector2D& Loc, const struct FVector& worldLoc);
	void ExecuteUbergraph_MiniMapCharacterIconPylons(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MiniMapCharacterIconPylons_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MiniMapCharacterIconPylons_C")
	}
	static class UMiniMapCharacterIconPylons_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMiniMapCharacterIconPylons_C>();
	}
};
DUMPER7_ASSERTS_UMiniMapCharacterIconPylons_C;

SDK_NAMESPACE_END
