#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewDeerBP

#include "Basic.hpp"

#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass NewDeerBP.NewDeerBP_C
// 0x0010 (0x0338 - 0x0328)
class ANewDeerBP_C final : public ADarwinDeer
{
public:
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NewDeerBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NewDeerBP_C")
	}
	static class ANewDeerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANewDeerBP_C>();
	}
};
DUMPER7_ASSERTS_ANewDeerBP_C;

SDK_NAMESPACE_END
