#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewTeammateWidgetBP

#include "Basic.hpp"

#include "NewTeammateWidgetBP_classes.hpp"
#include "NewTeammateWidgetBP_parameters.hpp"


SDK_NAMESPACE_START

// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventDamageNotification
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinDamageTypeEnum                   Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   attackerUniqueID                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   victimUniqueID                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventDamageNotification(EDarwinDamageTypeEnum Type, float Damage, int32 attackerUniqueID, int32 victimUniqueID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventDamageNotification");

	Params::NewTeammateWidgetBP_C_EventDamageNotification Parms{};

	Parms.Type = Type;
	Parms.Damage = Damage;
	Parms.attackerUniqueID = attackerUniqueID;
	Parms.victimUniqueID = victimUniqueID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventPlayerCraftedPower
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventPlayerCraftedPower(int32 PlayerID, EDarwinItemTypeEnum PowerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventPlayerCraftedPower");

	Params::NewTeammateWidgetBP_C_EventPlayerCraftedPower Parms{};

	Parms.PlayerID = PlayerID;
	Parms.PowerType = PowerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventPlayerIsDead
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PodiumRank                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventPlayerIsDead(int32 PlayerID, int32 PodiumRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventPlayerIsDead");

	Params::NewTeammateWidgetBP_C_EventPlayerIsDead Parms{};

	Parms.PlayerID = PlayerID;
	Parms.PodiumRank = PodiumRank;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventPlayerSpeakEnd
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   UniqueID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventPlayerSpeakEnd(int32 UniqueID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventPlayerSpeakEnd");

	Params::NewTeammateWidgetBP_C_EventPlayerSpeakEnd Parms{};

	Parms.UniqueID = UniqueID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventPlayerSpeakStart
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   UniqueID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventPlayerSpeakStart(int32 UniqueID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventPlayerSpeakStart");

	Params::NewTeammateWidgetBP_C_EventPlayerSpeakStart Parms{};

	Parms.UniqueID = UniqueID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventRemoveBeholderFromTeam
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   TeamIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   beholderID                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventRemoveBeholderFromTeam(int32 TeamIndex, int32 beholderID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventRemoveBeholderFromTeam");

	Params::NewTeammateWidgetBP_C_EventRemoveBeholderFromTeam Parms{};

	Parms.TeamIndex = TeamIndex;
	Parms.beholderID = beholderID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventRemovePlayerFromTeam
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   TeamIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventRemovePlayerFromTeam(int32 TeamIndex, int32 PlayerID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventRemovePlayerFromTeam");

	Params::NewTeammateWidgetBP_C_EventRemovePlayerFromTeam Parms{};

	Parms.TeamIndex = TeamIndex;
	Parms.PlayerID = PlayerID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventUpdateAvatarTexture
// (Event, Public, BlueprintEvent)
// Parameters:
// class UTexture*                         avatar                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventUpdateAvatarTexture(class UTexture* avatar, int32 PlayerID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventUpdateAvatarTexture");

	Params::NewTeammateWidgetBP_C_EventUpdateAvatarTexture Parms{};

	Parms.avatar = avatar;
	Parms.PlayerID = PlayerID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventUpdatePlayerColdFactor
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   coldFactorNormalized                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventUpdatePlayerColdFactor(float coldFactorNormalized, int32 PlayerID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventUpdatePlayerColdFactor");

	Params::NewTeammateWidgetBP_C_EventUpdatePlayerColdFactor Parms{};

	Parms.coldFactorNormalized = coldFactorNormalized;
	Parms.PlayerID = PlayerID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.EventUpdatePlayerHealth
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   healthNormalized                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::EventUpdatePlayerHealth(float healthNormalized, int32 PlayerID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "EventUpdatePlayerHealth");

	Params::NewTeammateWidgetBP_C_EventUpdatePlayerHealth Parms{};

	Parms.healthNormalized = healthNormalized;
	Parms.PlayerID = PlayerID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.ExecuteUbergraph_NewTeammateWidgetBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::ExecuteUbergraph_NewTeammateWidgetBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "ExecuteUbergraph_NewTeammateWidgetBP");

	Params::NewTeammateWidgetBP_C_ExecuteUbergraph_NewTeammateWidgetBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.Initialize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateID_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    beholder_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    captain_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::Initialize(int32 TeammateID_0, bool beholder_0, bool captain_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "Initialize");

	Params::NewTeammateWidgetBP_C_Initialize Parms{};

	Parms.TeammateID_0 = TeammateID_0;
	Parms.beholder_0 = beholder_0;
	Parms.captain_0 = captain_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.SDPowerSelected
// (BlueprintCallable, BlueprintEvent)

void UNewTeammateWidgetBP_C::SDPowerSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "SDPowerSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.SDPowerUnSelected
// (BlueprintCallable, BlueprintEvent)

void UNewTeammateWidgetBP_C::SDPowerUnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "SDPowerUnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewTeammateWidgetBP.NewTeammateWidgetBP_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewTeammateWidgetBP_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewTeammateWidgetBP_C", "Tick");

	Params::NewTeammateWidgetBP_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
