#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OptionsToggle

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function OptionsToggle.OptionsToggle_C.BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct OptionsToggle_C_BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature;

// Function OptionsToggle.OptionsToggle_C.ChangeCheckState
// 0x0001 (0x0001 - 0x0000)
struct OptionsToggle_C_ChangeCheckState final
{
public:
	bool                                          IsChecked_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_ChangeCheckState;

// Function OptionsToggle.OptionsToggle_C.ExecuteUbergraph_OptionsToggle
// 0x0088 (0x0088 - 0x0000)
struct OptionsToggle_C_ExecuteUbergraph_OptionsToggle final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0010)(HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked;             // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x001C(0x0008)(NoDestructor)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0028(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInputAnalogStickState_StickX;          // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetInputAnalogStickState_StickY;          // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_DoubleDouble_ReturnValue;        // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChecked_ReturnValue;                    // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsChecked;                      // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_NotEqual_DoubleDouble_A_ImplicitCast;     // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_ExecuteUbergraph_OptionsToggle;

// Function OptionsToggle.OptionsToggle_C.Is Hovered
// 0x0001 (0x0001 - 0x0000)
struct OptionsToggle_C_Is_Hovered final
{
public:
	bool                                          CallFunc_IsHovered_ReturnValue;                    // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_Is_Hovered;

// Function OptionsToggle.OptionsToggle_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct OptionsToggle_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
DUMPER7_ASSERTS_OptionsToggle_C_OnAddedToFocusPath;

// Function OptionsToggle.OptionsToggle_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct OptionsToggle_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_PreConstruct;

// Function OptionsToggle.OptionsToggle_C.Set focus state
// 0x0960 (0x0960 - 0x0000)
struct OptionsToggle_C_Set_focus_state final
{
public:
	bool                                          focus_state;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0xF];                                        // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCheckBoxStyle                         NewLocalVar_0;                                     // 0x0010(0x0950)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_OptionsToggle_C_Set_focus_state;

// Function OptionsToggle.OptionsToggle_C.Set state
// 0x0001 (0x0001 - 0x0000)
struct OptionsToggle_C_Set_state final
{
public:
	bool                                          Check_State;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_Set_state;

// Function OptionsToggle.OptionsToggle_C.set unchecked style
// 0x14C0 (0x14C0 - 0x0000)
struct OptionsToggle_C_set_unchecked_style final
{
public:
	bool                                          Unchecked_Is_red_0;                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0xF];                                        // 0x0001(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0010(0x00B0)()
	struct FCheckBoxStyle                         K2Node_MakeStruct_CheckBoxStyle;                   // 0x00C0(0x0950)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_1;                    // 0x0A10(0x00B0)()
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush_2;                    // 0x0AC0(0x00B0)()
	struct FCheckBoxStyle                         K2Node_MakeStruct_CheckBoxStyle_1;                 // 0x0B70(0x0950)()
};
DUMPER7_ASSERTS_OptionsToggle_C_set_unchecked_style;

// Function OptionsToggle.OptionsToggle_C.Tick
// 0x003C (0x003C - 0x0000)
struct OptionsToggle_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_Tick;

// Function OptionsToggle.OptionsToggle_C.Toggle
// 0x0002 (0x0002 - 0x0000)
struct OptionsToggle_C_Toggle final
{
public:
	bool                                          CallFunc_IsChecked_ReturnValue;                    // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_OptionsToggle_C_Toggle;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
