#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PowerSlot_d2

#include "Basic.hpp"

#include "PowerSlot_d2_classes.hpp"
#include "PowerSlot_d2_parameters.hpp"


SDK_NAMESPACE_START

// Function PowerSlot_d2.PowerSlot_d2_C.ActivatePower
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::ActivatePower()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "ActivatePower");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventInputRebindSucceeded
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      ActionToRebind                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      NewKeyName                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPowerSlot_d2_C::EventInputRebindSucceeded(const class FName& ActionToRebind, const class FText& NewKeyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventInputRebindSucceeded");

	Params::PowerSlot_d2_C_EventInputRebindSucceeded Parms{};

	Parms.ActionToRebind = ActionToRebind;
	Parms.NewKeyName = std::move(NewKeyName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventInputResetToDefault
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventInputResetToDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventInputResetToDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventInputSourceChanged
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventInputSourceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventInputSourceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventInventorySlotChanged
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDarwinItemTypeEnum                     Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Number                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventInventorySlotChanged(int32 Index_0, EDarwinItemTypeEnum Type, int32 Number)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventInventorySlotChanged");

	Params::PowerSlot_d2_C_EventInventorySlotChanged Parms{};

	Parms.Index_0 = Index_0;
	Parms.Type = Type;
	Parms.Number = Number;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventPowerAlmostReady
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventPowerAlmostReady(EDarwinItemTypeEnum PowerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventPowerAlmostReady");

	Params::PowerSlot_d2_C_EventPowerAlmostReady Parms{};

	Parms.PowerType = PowerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventPowerCooldownStart
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventPowerCooldownStart(EDarwinItemTypeEnum PowerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventPowerCooldownStart");

	Params::PowerSlot_d2_C_EventPowerCooldownStart Parms{};

	Parms.PowerType = PowerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventPowerOff
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventPowerOff(EDarwinItemTypeEnum PowerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventPowerOff");

	Params::PowerSlot_d2_C_EventPowerOff Parms{};

	Parms.PowerType = PowerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventPowerOn
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventPowerOn(EDarwinItemTypeEnum PowerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventPowerOn");

	Params::PowerSlot_d2_C_EventPowerOn Parms{};

	Parms.PowerType = PowerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventPowerReady
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventPowerReady(EDarwinItemTypeEnum PowerType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventPowerReady");

	Params::PowerSlot_d2_C_EventPowerReady Parms{};

	Parms.PowerType = PowerType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventTeleportAimEnd
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventTeleportAimEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventTeleportAimEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventTeleportAimStart
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventTeleportAimStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventTeleportAimStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventTeleportAlmostReady
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventTeleportAlmostReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventTeleportAlmostReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventTeleportCooldownStart
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventTeleportCooldownStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventTeleportCooldownStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventTeleportReady
// (Event, Public, BlueprintEvent)

void UPowerSlot_d2_C::EventTeleportReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventTeleportReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventUpdateCraftableItemIcons
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     ItemType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventUpdateCraftableItemIcons(EDarwinItemTypeEnum ItemType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventUpdateCraftableItemIcons");

	Params::PowerSlot_d2_C_EventUpdateCraftableItemIcons Parms{};

	Parms.ItemType = ItemType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventUpdatePowerCooldown
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TimeLeft                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventUpdatePowerCooldown(EDarwinItemTypeEnum PowerType, float Value, int32 TimeLeft)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventUpdatePowerCooldown");

	Params::PowerSlot_d2_C_EventUpdatePowerCooldown Parms{};

	Parms.PowerType = PowerType;
	Parms.Value = Value;
	Parms.TimeLeft = TimeLeft;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventUpdatePowerDuration
// (Event, Public, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     PowerType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TimeLeft                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventUpdatePowerDuration(EDarwinItemTypeEnum PowerType, float Value, int32 TimeLeft)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventUpdatePowerDuration");

	Params::PowerSlot_d2_C_EventUpdatePowerDuration Parms{};

	Parms.PowerType = PowerType;
	Parms.Value = Value;
	Parms.TimeLeft = TimeLeft;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.EventUpdateTeleportCooldown
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TimeLeft                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::EventUpdateTeleportCooldown(float Value, int32 TimeLeft)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "EventUpdateTeleportCooldown");

	Params::PowerSlot_d2_C_EventUpdateTeleportCooldown Parms{};

	Parms.Value = Value;
	Parms.TimeLeft = TimeLeft;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.ExecuteUbergraph_PowerSlot_d2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::ExecuteUbergraph_PowerSlot_d2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "ExecuteUbergraph_PowerSlot_d2");

	Params::PowerSlot_d2_C_ExecuteUbergraph_PowerSlot_d2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.input mode
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::input_mode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "input mode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "PreConstruct");

	Params::PowerSlot_d2_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.set bg
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::set_bg(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "set bg");

	Params::PowerSlot_d2_C_set_bg Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.Set binds
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::Set_binds(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "Set binds");

	Params::PowerSlot_d2_C_Set_binds Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.set icon big
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::set_icon_big()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "set icon big");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.set icon small
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::set_icon_small()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "set icon small");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.SetSlotTypeAndIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     InSlotType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPowerSlot_d2_C::SetSlotTypeAndIcon(EDarwinItemTypeEnum InSlotType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "SetSlotTypeAndIcon");

	Params::PowerSlot_d2_C_SetSlotTypeAndIcon Parms{};

	Parms.InSlotType = InSlotType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PowerSlot_d2.PowerSlot_d2_C.SetToCooldown
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::SetToCooldown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "SetToCooldown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.SetToCrafted
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::SetToCrafted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "SetToCrafted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.SetToPowerOn
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::SetToPowerOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "SetToPowerOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.SetToPowerReady
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::SetToPowerReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "SetToPowerReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.SetToUnCrafted
// (Public, BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::SetToUnCrafted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "SetToUnCrafted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PowerSlot_d2.PowerSlot_d2_C.UpdateSlot
// (BlueprintCallable, BlueprintEvent)

void UPowerSlot_d2_C::UpdateSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PowerSlot_d2_C", "UpdateSlot");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
