#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrivateMatchStart

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Darwin_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PrivateMatchStart.PrivateMatchStart_C.KeyBiding
// 0x0020 (0x0020 - 0x0000)
struct PrivateMatchStart_C_KeyBiding final
{
public:
	bool                                          CallFunc_GetIsUsingGamepad_ReturnValue;            // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UDarwinGameInstance*                    K2Node_DynamicCast_AsDarwin_Game_Instance;         // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrivateMatchStart_C_KeyBiding;

// Function PrivateMatchStart.PrivateMatchStart_C.EventUpdatePrivateMatchTimer
// 0x0010 (0x0010 - 0x0000)
struct PrivateMatchStart_C_EventUpdatePrivateMatchTimer final
{
public:
	class FString                                 timeUntilRestart;                                  // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrivateMatchStart_C_EventUpdatePrivateMatchTimer;

// Function PrivateMatchStart.PrivateMatchStart_C.EventGameModeChanged
// 0x0010 (0x0010 - 0x0000)
struct PrivateMatchStart_C_EventGameModeChanged final
{
public:
	EDarwinGameMode                               NewMode;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  local_pawn;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrivateMatchStart_C_EventGameModeChanged;

// Function PrivateMatchStart.PrivateMatchStart_C.EventIsPrivateMatchOwner
// 0x0010 (0x0010 - 0x0000)
struct PrivateMatchStart_C_EventIsPrivateMatchOwner final
{
public:
	class FString                                 Password;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrivateMatchStart_C_EventIsPrivateMatchOwner;

// Function PrivateMatchStart.PrivateMatchStart_C.EventUpdateAutoStartTimer
// 0x0010 (0x0010 - 0x0000)
struct PrivateMatchStart_C_EventUpdateAutoStartTimer final
{
public:
	class FString                                 timeUntilStart;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrivateMatchStart_C_EventUpdateAutoStartTimer;

// Function PrivateMatchStart.PrivateMatchStart_C.ExecuteUbergraph_PrivateMatchStart
// 0x0090 (0x0090 - 0x0000)
struct PrivateMatchStart_C_ExecuteUbergraph_PrivateMatchStart final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0010)(HasGetValueTypeHash)
	class FString                                 K2Node_Event_timeUntilRestart;                     // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0028(0x0010)()
	class FString                                 CallFunc_GetCurrentLevelName_ReturnValue;          // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInTrainingRoom_ReturnValue;             // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDarwinGameMode                               K2Node_Event_newMode;                              // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_Event_local_pawn;                           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAuctionOpened_ReturnValue;              // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5A[0x6];                                       // 0x005A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_password;                             // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Event_timeUntilStart;                       // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0080(0x0010)()
};
DUMPER7_ASSERTS_PrivateMatchStart_C_ExecuteUbergraph_PrivateMatchStart;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
