#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProfilingStats

#include "Basic.hpp"

#include "ProfilingStats_classes.hpp"
#include "ProfilingStats_parameters.hpp"


SDK_NAMESPACE_START

// Function ProfilingStats.ProfilingStats_C.EventUpdateProfilingStats
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FDarwinProfilingStats&     Stats                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UProfilingStats_C::EventUpdateProfilingStats(const struct FDarwinProfilingStats& Stats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ProfilingStats_C", "EventUpdateProfilingStats");

	Params::ProfilingStats_C_EventUpdateProfilingStats Parms{};

	Parms.Stats = std::move(Stats);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ProfilingStats.ProfilingStats_C.ExecuteUbergraph_ProfilingStats
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UProfilingStats_C::ExecuteUbergraph_ProfilingStats(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ProfilingStats_C", "ExecuteUbergraph_ProfilingStats");

	Params::ProfilingStats_C_ExecuteUbergraph_ProfilingStats Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ProfilingStats.ProfilingStats_C.RoundToOneDecimal
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UProfilingStats_C::RoundToOneDecimal(double Value, double* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ProfilingStats_C", "RoundToOneDecimal");

	Params::ProfilingStats_C_RoundToOneDecimal Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function ProfilingStats.ProfilingStats_C.UpdateStats
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDarwinProfilingStats&     Stats                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UProfilingStats_C::UpdateStats(const struct FDarwinProfilingStats& Stats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ProfilingStats_C", "UpdateStats");

	Params::ProfilingStats_C_UpdateStats Parms{};

	Parms.Stats = std::move(Stats);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ProfilingStats.ProfilingStats_C.UpdateStatsExtended
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDarwinProfilingStats&     Stats                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UProfilingStats_C::UpdateStatsExtended(const struct FDarwinProfilingStats& Stats)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ProfilingStats_C", "UpdateStatsExtended");

	Params::ProfilingStats_C_UpdateStatsExtended Parms{};

	Parms.Stats = std::move(Stats);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
