#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SalesTab_Featured

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass SalesTab_Featured.SalesTab_Featured_C
// 0x0078 (0x0A10 - 0x0998)
class USalesTab_Featured_C final : public UDarwinMainMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0998(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPurchaseTierCard_C*                    PurchaseTierCard;                                  // 0x09A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly8;                              // 0x09A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly7;                              // 0x09B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly6;                              // 0x09B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly5;                              // 0x09C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly4;                              // 0x09C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly3;                              // 0x09D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly2;                              // 0x09D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongItemCard_C*                        LongItemCard_weekly1;                              // 0x09E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBattlePassCard_C*                      BattlePassCard;                                    // 0x09E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNewSalesMenu_C*                        SalesMenu;                                         // 0x09F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         SelectedCard;                                      // 0x09F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSelectingFirstCard;                              // 0x09FC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9FD[0x3];                                      // 0x09FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ULongItemCard_C*>                ItemCards;                                         // 0x0A00(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void BndEvt__LongItemCard_weekly1_K2Node_ComponentBoundEvent_7_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly2_K2Node_ComponentBoundEvent_8_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly3_K2Node_ComponentBoundEvent_9_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly4_K2Node_ComponentBoundEvent_10_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly5_K2Node_ComponentBoundEvent_11_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly6_K2Node_ComponentBoundEvent_12_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly7_K2Node_ComponentBoundEvent_13_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BndEvt__LongItemCard_weekly8_K2Node_ComponentBoundEvent_14_Click_on_item_card__DelegateSignature(class ULongItemCard_C* item_card, const struct FDarwinUMGSecondaryShopFeaturedItem& shop_item);
	void BuyCurrentSelection();
	void Construct();
	void EventInputSourceChanged();
	void EventMenuClick();
	void EventMenuLeft(bool bThumbstick);
	void EventMenuRight(bool bThumbstick);
	void ExecuteUbergraph_SalesTab_Featured(int32 EntryPoint);
	void Init_Parent(class UNewSalesMenu_C* Parent);
	void IsWidgetActive(bool* Is_active);
	void select_a_card();
	void UnselectAllCards();
	void UpdateCurrentSelection(int32 SelectedCardIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SalesTab_Featured_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SalesTab_Featured_C")
	}
	static class USalesTab_Featured_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USalesTab_Featured_C>();
	}
};
DUMPER7_ASSERTS_USalesTab_Featured_C;

SDK_NAMESPACE_END
