#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowDirectorSidePannel

#include "Basic.hpp"

#include "ShowDirectorSidePannel_classes.hpp"
#include "ShowDirectorSidePannel_parameters.hpp"


SDK_NAMESPACE_START

// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UShowDirectorSidePannel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowDirectorSidePannel_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "Tick");

	Params::ShowDirectorSidePannel_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.EventShiftKeyPressed
// (Event, Public, BlueprintEvent)

void UShowDirectorSidePannel_C::EventShiftKeyPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "EventShiftKeyPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.EventShiftKeyReleased
// (Event, Public, BlueprintEvent)

void UShowDirectorSidePannel_C::EventShiftKeyReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "EventShiftKeyReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_1_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_1_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_1_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_2_K2Node_ComponentBoundEvent_56_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_2_K2Node_ComponentBoundEvent_56_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_2_K2Node_ComponentBoundEvent_56_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_3_K2Node_ComponentBoundEvent_170_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_3_K2Node_ComponentBoundEvent_170_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_3_K2Node_ComponentBoundEvent_170_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_4_K2Node_ComponentBoundEvent_187_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_4_K2Node_ComponentBoundEvent_187_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_4_K2Node_ComponentBoundEvent_187_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_5_K2Node_ComponentBoundEvent_208_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_5_K2Node_ComponentBoundEvent_208_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_5_K2Node_ComponentBoundEvent_208_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_6_K2Node_ComponentBoundEvent_230_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_6_K2Node_ComponentBoundEvent_230_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_6_K2Node_ComponentBoundEvent_230_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_7_K2Node_ComponentBoundEvent_253_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_7_K2Node_ComponentBoundEvent_253_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_7_K2Node_ComponentBoundEvent_253_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_8_K2Node_ComponentBoundEvent_277_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_8_K2Node_ComponentBoundEvent_277_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_8_K2Node_ComponentBoundEvent_277_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_9_K2Node_ComponentBoundEvent_302_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_9_K2Node_ComponentBoundEvent_302_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_9_K2Node_ComponentBoundEvent_302_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_10_K2Node_ComponentBoundEvent_328_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_10_K2Node_ComponentBoundEvent_328_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_10_K2Node_ComponentBoundEvent_328_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_11_K2Node_ComponentBoundEvent_365_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_11_K2Node_ComponentBoundEvent_365_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_11_K2Node_ComponentBoundEvent_365_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowDirectorSidePannel_C::BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnFloatValueChangedEvent__DelegateSignature");

	Params::ShowDirectorSidePannel_C_BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Slider_0_K2Node_ComponentBoundEvent_27_OnMouseCaptureBeginEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Slider_0_K2Node_ComponentBoundEvent_27_OnMouseCaptureBeginEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Slider_0_K2Node_ComponentBoundEvent_27_OnMouseCaptureBeginEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Slider_0_K2Node_ComponentBoundEvent_38_OnControllerCaptureBeginEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Slider_0_K2Node_ComponentBoundEvent_38_OnControllerCaptureBeginEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Slider_0_K2Node_ComponentBoundEvent_38_OnControllerCaptureBeginEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Slider_0_K2Node_ComponentBoundEvent_59_OnMouseCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Slider_0_K2Node_ComponentBoundEvent_59_OnMouseCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Slider_0_K2Node_ComponentBoundEvent_59_OnMouseCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnControllerCaptureEndEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnControllerCaptureEndEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Slider_0_K2Node_ComponentBoundEvent_78_OnControllerCaptureEndEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__CheckBox_Proximity_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowDirectorSidePannel_C::BndEvt__CheckBox_Proximity_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__CheckBox_Proximity_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::ShowDirectorSidePannel_C_BndEvt__CheckBox_Proximity_K2Node_ComponentBoundEvent_45_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__CheckBox_ALL_K2Node_ComponentBoundEvent_105_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowDirectorSidePannel_C::BndEvt__CheckBox_ALL_K2Node_ComponentBoundEvent_105_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__CheckBox_ALL_K2Node_ComponentBoundEvent_105_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::ShowDirectorSidePannel_C_BndEvt__CheckBox_ALL_K2Node_ComponentBoundEvent_105_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_13_K2Node_ComponentBoundEvent_1207_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_13_K2Node_ComponentBoundEvent_1207_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_13_K2Node_ComponentBoundEvent_1207_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_15_K2Node_ComponentBoundEvent_1263_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_15_K2Node_ComponentBoundEvent_1263_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_15_K2Node_ComponentBoundEvent_1263_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_18_K2Node_ComponentBoundEvent_1611_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_18_K2Node_ComponentBoundEvent_1611_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_18_K2Node_ComponentBoundEvent_1611_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.BndEvt__Button_12_K2Node_ComponentBoundEvent_141_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UShowDirectorSidePannel_C::BndEvt__Button_12_K2Node_ComponentBoundEvent_141_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "BndEvt__Button_12_K2Node_ComponentBoundEvent_141_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShowDirectorSidePannel.ShowDirectorSidePannel_C.ExecuteUbergraph_ShowDirectorSidePannel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShowDirectorSidePannel_C::ExecuteUbergraph_ShowDirectorSidePannel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShowDirectorSidePannel_C", "ExecuteUbergraph_ShowDirectorSidePannel");

	Params::ShowDirectorSidePannel_C_ExecuteUbergraph_ShowDirectorSidePannel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
