#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundWheelTextInfo

#include "Basic.hpp"

#include "SoundWheelTextInfo_classes.hpp"
#include "SoundWheelTextInfo_parameters.hpp"


SDK_NAMESPACE_START

// Function SoundWheelTextInfo.SoundWheelTextInfo_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USoundWheelTextInfo_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.EventGameStartsNow
// (Event, Public, BlueprintEvent)

void USoundWheelTextInfo_C::EventGameStartsNow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "EventGameStartsNow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.EventInputSourceChanged
// (Event, Public, BlueprintEvent)

void USoundWheelTextInfo_C::EventInputSourceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "EventInputSourceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.ExecuteUbergraph_SoundWheelTextInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundWheelTextInfo_C::ExecuteUbergraph_SoundWheelTextInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "ExecuteUbergraph_SoundWheelTextInfo");

	Params::SoundWheelTextInfo_C_ExecuteUbergraph_SoundWheelTextInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.Get_TextBlock_38_ColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FSlateColor USoundWheelTextInfo_C::Get_TextBlock_38_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "Get_TextBlock_38_ColorAndOpacity_0");

	Params::SoundWheelTextInfo_C_Get_TextBlock_38_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.Hovered
// (BlueprintCallable, BlueprintEvent)

void USoundWheelTextInfo_C::Hovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "Hovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.Initialize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EDarwinItemTypeEnum                     ItemType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundWheelTextInfo_C::Initialize(EDarwinItemTypeEnum ItemType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "Initialize");

	Params::SoundWheelTextInfo_C_Initialize Parms{};

	Parms.ItemType = ItemType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.SetGlobal
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Global                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundWheelTextInfo_C::SetGlobal(bool Global)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "SetGlobal");

	Params::SoundWheelTextInfo_C_SetGlobal Parms{};

	Parms.Global = Global;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.SetSoundId
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SoundId_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USoundWheelTextInfo_C::SetSoundId(int32 SoundId_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "SetSoundId");

	Params::SoundWheelTextInfo_C_SetSoundId Parms{};

	Parms.SoundId_0 = SoundId_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SoundWheelTextInfo.SoundWheelTextInfo_C.Unhovered
// (BlueprintCallable, BlueprintEvent)

void USoundWheelTextInfo_C::Unhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SoundWheelTextInfo_C", "Unhovered");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
