#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StarterPackCard

#include "Basic.hpp"

#include "StarterPackCard_classes.hpp"
#include "StarterPackCard_parameters.hpp"


SDK_NAMESPACE_START

// Function StarterPackCard.StarterPackCard_C.Unselect
// (Public, BlueprintCallable, BlueprintEvent)

void UStarterPackCard_C::Unselect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "Unselect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.Select
// (Public, BlueprintCallable, BlueprintEvent)

void UStarterPackCard_C::Select()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "Select");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.UpdatePackState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UStarterPackCard_C::UpdatePackState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "UpdatePackState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStarterPackCard_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "Tick");

	Params::StarterPackCard_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StarterPackCard.StarterPackCard_C.BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UStarterPackCard_C::BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UStarterPackCard_C::BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UStarterPackCard_C::BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "BndEvt__Button_StarterPack_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UStarterPackCard_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.EventFinalizePrimaryShopTransactionEnd
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   SpecialPackId                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    transactionSucceeded                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStarterPackCard_C::EventFinalizePrimaryShopTransactionEnd(int32 SpecialPackId, bool transactionSucceeded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "EventFinalizePrimaryShopTransactionEnd");

	Params::StarterPackCard_C_EventFinalizePrimaryShopTransactionEnd Parms{};

	Parms.SpecialPackId = SpecialPackId;
	Parms.transactionSucceeded = transactionSucceeded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StarterPackCard.StarterPackCard_C.Buy
// (BlueprintCallable, BlueprintEvent)

void UStarterPackCard_C::Buy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "Buy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function StarterPackCard.StarterPackCard_C.set market as parent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMarket_C*                        NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UStarterPackCard_C::set_market_as_parent(class UMarket_C* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "set market as parent");

	Params::StarterPackCard_C_set_market_as_parent Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StarterPackCard.StarterPackCard_C.ExecuteUbergraph_StarterPackCard
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStarterPackCard_C::ExecuteUbergraph_StarterPackCard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StarterPackCard_C", "ExecuteUbergraph_StarterPackCard");

	Params::StarterPackCard_C_ExecuteUbergraph_StarterPackCard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
