#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ToggleButton

#include "Basic.hpp"

#include "ToggleButton_classes.hpp"
#include "ToggleButton_parameters.hpp"


SDK_NAMESPACE_START

// Function ToggleButton.ToggleButton_C.BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsChecked                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UToggleButton_C::BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature(bool bIsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature");

	Params::ToggleButton_C_BndEvt__CheckBox_0_K2Node_ComponentBoundEvent_5_OnCheckBoxComponentStateChanged__DelegateSignature Parms{};

	Parms.bIsChecked = bIsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ToggleButton.ToggleButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UToggleButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ToggleButton.ToggleButton_C.ExecuteUbergraph_ToggleButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UToggleButton_C::ExecuteUbergraph_ToggleButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "ExecuteUbergraph_ToggleButton");

	Params::ToggleButton_C_ExecuteUbergraph_ToggleButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ToggleButton.ToggleButton_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UToggleButton_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "OnAddedToFocusPath");

	Params::ToggleButton_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ToggleButton.ToggleButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UToggleButton_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "PreConstruct");

	Params::ToggleButton_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ToggleButton.ToggleButton_C.Set focus state
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    focus_state                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UToggleButton_C::Set_focus_state(bool focus_state)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "Set focus state");

	Params::ToggleButton_C_Set_focus_state Parms{};

	Parms.focus_state = focus_state;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ToggleButton.ToggleButton_C.Set state
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Check_State                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UToggleButton_C::Set_state(bool Check_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "Set state");

	Params::ToggleButton_C_Set_state Parms{};

	Parms.Check_State = Check_State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ToggleButton.ToggleButton_C.Toggle
// (Public, BlueprintCallable, BlueprintEvent)

void UToggleButton_C::Toggle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ToggleButton_C", "Toggle");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
