#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TooltipMatchBonusUnavailable

#include "Basic.hpp"

#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass TooltipMatchBonusUnavailable.TooltipMatchBonusUnavailable_C
// 0x0010 (0x09A8 - 0x0998)
class UTooltipMatchBonusUnavailable_C final : public UDarwinMainMenuWidget
{
public:
	class UTextBlock*                             Title;                                             // 0x0998(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Body;                                              // 0x09A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Initialize(bool Is_first_win, const struct FTimespan& Time);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TooltipMatchBonusUnavailable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TooltipMatchBonusUnavailable_C")
	}
	static class UTooltipMatchBonusUnavailable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTooltipMatchBonusUnavailable_C>();
	}
};
DUMPER7_ASSERTS_UTooltipMatchBonusUnavailable_C;

SDK_NAMESPACE_END
