#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePass_level_Reward

#include "Basic.hpp"

#include "Darwin_structs.hpp"
#include "Darwin_classes.hpp"
#include "Engine_structs.hpp"
#include "NavigationRequest_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass BattlePass_level_Reward.BattlePass_level_Reward_C
// 0x00A0 (0x0A38 - 0x0998)
class UBattlePass_level_Reward_C final : public UDarwinMainMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0998(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             Level_Number;                                      // 0x09A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Premium;                                    // 0x09A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Header;                                     // 0x09B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Guest;                                      // 0x09B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBattlePass_UniqueReward_C*             BattlePass_UniqueReward_Guest;                     // 0x09C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBattlePass_UniqueReward_C*             BattlePass_UniqueReward_04;                        // 0x09C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBattlePass_UniqueReward_C*             BattlePass_UniqueReward_03;                        // 0x09D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBattlePass_UniqueReward_C*             BattlePass_UniqueReward_02;                        // 0x09D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBattlePass_UniqueReward_C*             BattlePass_UniqueReward_01;                        // 0x09E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 Item_Id, EItemType item_type, bool Is_locked)> On_hovered_Reward; // 0x09E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UBattlePass_UniqueReward_C*>     Unique_Rewards_Cards;                              // 0x09F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                          Widget_is_Focused;                                 // 0x0A08(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A09[0x3];                                      // 0x0A09(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Focused_button_index;                              // 0x0A0C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 Focus_CArd_Index)> Focus_Right;                              // 0x0A10(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(int32 Focus_CArd_Index)> Focus_Left;                               // 0x0A20(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          Next_Frame_Focus;                                  // 0x0A30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A31[0x3];                                      // 0x0A31(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Level;                                             // 0x0A34(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Unselect_all();
	void Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick);
	void Set_Is_Unlocked(int32 Card_Level);
	void Set_Gamepad_Navigation_On_focus(bool Focused_from_the_Left, int32 Focus_CArd_Index);
	void MoveSelection(ENavigationRequest Direction);
	void Initialize_Level_Reward(int32 Card_Level);
	void ExecuteUbergraph_BattlePass_level_Reward(int32 EntryPoint);
	void EventPlayerCommunityEventUpdated();
	void EventInputSourceChanged();
	void Construct();
	void BndEvt__BattlePass_UniqueReward_Guest_K2Node_ComponentBoundEvent_7_On_Hovered_Unique_reward__DelegateSignature(int32 Item_Id, EItemType item_type, bool Is_locked);
	void BndEvt__BattlePass_UniqueReward_04_K2Node_ComponentBoundEvent_3_On_Hovered_Unique_reward__DelegateSignature(int32 Item_Id, EItemType item_type, bool Is_locked);
	void BndEvt__BattlePass_UniqueReward_03_K2Node_ComponentBoundEvent_2_On_Hovered_Unique_reward__DelegateSignature(int32 Item_Id, EItemType item_type, bool Is_locked);
	void BndEvt__BattlePass_UniqueReward_02_K2Node_ComponentBoundEvent_1_On_Hovered_Unique_reward__DelegateSignature(int32 Item_Id, EItemType item_type, bool Is_locked);
	void BndEvt__BattlePass_UniqueReward_01_K2Node_ComponentBoundEvent_0_On_Hovered_Unique_reward__DelegateSignature(int32 Item_Id, EItemType item_type, bool Is_locked);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BattlePass_level_Reward_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BattlePass_level_Reward_C")
	}
	static class UBattlePass_level_Reward_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePass_level_Reward_C>();
	}
};
DUMPER7_ASSERTS_UBattlePass_level_Reward_C;

SDK_NAMESPACE_END
