#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePass_Storytab

#include "Basic.hpp"

#include "BattlePass_Storytab_classes.hpp"
#include "BattlePass_Storytab_parameters.hpp"


SDK_NAMESPACE_START

// Function BattlePass_Storytab.BattlePass_Storytab_C.BackAction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   HasConsumeBack                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::BackAction(bool* HasConsumeBack)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "BackAction");

	Params::BattlePass_Storytab_C_BackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HasConsumeBack != nullptr)
		*HasConsumeBack = Parms.HasConsumeBack;
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.BackFromCategoryContent
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::BackFromCategoryContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "BackFromCategoryContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.BndEvt__NavButton_Color_K2Node_ComponentBoundEvent_3_On Clicked__DelegateSignature
// (BlueprintEvent)

void UBattlePass_Storytab_C::BndEvt__NavButton_Color_K2Node_ComponentBoundEvent_3_On_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "BndEvt__NavButton_Color_K2Node_ComponentBoundEvent_3_On Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.DisplayLoreFromBattlePass
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    BattlePassName                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::DisplayLoreFromBattlePass(const class FString& BattlePassName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "DisplayLoreFromBattlePass");

	Params::BattlePass_Storytab_C_DisplayLoreFromBattlePass Parms{};

	Parms.BattlePassName = std::move(BattlePassName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventInputSourceChanged
// (Event, Public, BlueprintEvent)

void UBattlePass_Storytab_C::EventInputSourceChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventInputSourceChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuBack
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsEscape                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::EventMenuBack(bool bIsEscape)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuBack");

	Params::BattlePass_Storytab_C_EventMenuBack Parms{};

	Parms.bIsEscape = bIsEscape;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuClick
// (Event, Public, BlueprintEvent)

void UBattlePass_Storytab_C::EventMenuClick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuClick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuDown
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bThumbstick                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::EventMenuDown(bool bThumbstick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuDown");

	Params::BattlePass_Storytab_C_EventMenuDown Parms{};

	Parms.bThumbstick = bThumbstick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuLeft
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bThumbstick                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::EventMenuLeft(bool bThumbstick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuLeft");

	Params::BattlePass_Storytab_C_EventMenuLeft Parms{};

	Parms.bThumbstick = bThumbstick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuLeftPagePressed
// (Event, Public, BlueprintEvent)

void UBattlePass_Storytab_C::EventMenuLeftPagePressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuLeftPagePressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuRight
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bThumbstick                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::EventMenuRight(bool bThumbstick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuRight");

	Params::BattlePass_Storytab_C_EventMenuRight Parms{};

	Parms.bThumbstick = bThumbstick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuRightPagePressed
// (Event, Public, BlueprintEvent)

void UBattlePass_Storytab_C::EventMenuRightPagePressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuRightPagePressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.EventMenuUp
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bThumbstick                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::EventMenuUp(bool bThumbstick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "EventMenuUp");

	Params::BattlePass_Storytab_C_EventMenuUp Parms{};

	Parms.bThumbstick = bThumbstick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.ExecuteUbergraph_BattlePass_Storytab
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::ExecuteUbergraph_BattlePass_Storytab(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "ExecuteUbergraph_BattlePass_Storytab");

	Params::BattlePass_Storytab_C_ExecuteUbergraph_BattlePass_Storytab Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.GotoCategory
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    BattlePassName                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::GotoCategory(const class FString& BattlePassName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "GotoCategory");

	Params::BattlePass_Storytab_C_GotoCategory Parms{};

	Parms.BattlePassName = std::move(BattlePassName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    FromOptions_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::Initialize(bool FromOptions_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "Initialize");

	Params::BattlePass_Storytab_C_Initialize Parms{};

	Parms.FromOptions_0 = FromOptions_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.is Widget Active
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Active                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::is_Widget_Active(bool* Active)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "is Widget Active");

	Params::BattlePass_Storytab_C_is_Widget_Active Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Active != nullptr)
		*Active = Parms.Active;
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveCategoryDown
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveCategoryDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveCategoryDown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveCategoryLeft
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveCategoryLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveCategoryLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveCategoryRight
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveCategoryRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveCategoryRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveCategoryUp
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveCategoryUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveCategoryUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveLoreDown
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveLoreDown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveLoreDown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveLoreLeft
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveLoreLeft()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveLoreLeft");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveLoreRight
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveLoreRight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveLoreRight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.MoveLoreUp
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::MoveLoreUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "MoveLoreUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.On clicked lore card
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Lore_Id                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    Event_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::On_clicked_lore_card(int32 Lore_Id, const class FString& Event_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "On clicked lore card");

	Params::BattlePass_Storytab_C_On_clicked_lore_card Parms{};

	Parms.Lore_Id = Lore_Id;
	Parms.Event_Name = std::move(Event_Name);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.On Hovered Lore Card
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Lore_Id                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::On_Hovered_Lore_Card(int32 Lore_Id)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "On Hovered Lore Card");

	Params::BattlePass_Storytab_C_On_Hovered_Lore_Card Parms{};

	Parms.Lore_Id = Lore_Id;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.On open Story tab
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBattlePassD2_C*                  BattlePassD2                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::On_open_Story_tab(class UBattlePassD2_C* BattlePassD2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "On open Story tab");

	Params::BattlePass_Storytab_C_On_open_Story_tab Parms{};

	Parms.BattlePassD2 = BattlePassD2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.RefreshGamepadVisibilities
// (BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::RefreshGamepadVisibilities()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "RefreshGamepadVisibilities");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.SelectACategory
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::SelectACategory(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "SelectACategory");

	Params::BattlePass_Storytab_C_SelectACategory Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.Set gamepad selection
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Select_card_Id                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::Set_gamepad_selection(int32 Select_card_Id)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "Set gamepad selection");

	Params::BattlePass_Storytab_C_Set_gamepad_selection Parms{};

	Parms.Select_card_Id = Select_card_Id;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.Set Parent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBattlePassD2_C*                  Battle_Pass_D2_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBattlePass_Storytab_C::Set_Parent(class UBattlePassD2_C* Battle_Pass_D2_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "Set Parent");

	Params::BattlePass_Storytab_C_Set_Parent Parms{};

	Parms.Battle_Pass_D2_0 = Battle_Pass_D2_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.UnselectAllCategories
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::UnselectAllCategories()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "UnselectAllCategories");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePass_Storytab.BattlePass_Storytab_C.UnselectAllLore
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePass_Storytab_C::UnselectAllLore()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePass_Storytab_C", "UnselectAllLore");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
