#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CurrencyCount

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass CurrencyCount.CurrencyCount_C
// 0x0090 (0x0A28 - 0x0998)
class UCurrencyCount_C final : public UDarwinMainMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0998(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             TextBlock_Plus;                                    // 0x09A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_duplicategets;                           // 0x09A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x09B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x09B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButtonBindImage_C*                     GamepadPressRightStickIcon;                        // 0x09C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CurrentCurrency;                                   // 0x09C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Add;                                        // 0x09D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       get_ramens;                                        // 0x09D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       update_current;                                    // 0x09E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	bool                                          Invite_button_hovered;                             // 0x09E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Invite_button_pressed;                             // 0x09E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9EA[0x2];                                      // 0x09EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Ramen_Amount;                                      // 0x09EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMyNameAndLevel_C*                      My_name_and_level;                                 // 0x09F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMainMenu_C*                            Main_Menu;                                         // 0x09F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         difference;                                        // 0x0A00(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A04[0x4];                                      // 0x0A04(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              Add_curency;                                       // 0x0A08(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UNewMainMenuTest_C*                     New_Main_Menu;                                     // 0x0A18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         ActiveTransactions;                                // 0x0A20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          transactionSucceeded;                              // 0x0A24(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void CalculateWalletDifference(int32* RamenDifference);
	void UpdateButtonsState();
	void UpdateMoney();
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature();
	void Construct();
	void EventPlayerProfileReceived(const class FString& DisplayName, const struct FDarwinPlayerProgression& PlayerProgression);
	void Main_Menu_parents(class UMyNameAndLevel_C* Parent, class UMainMenu_C* NewParam);
	void BndEvt__Button_0_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature();
	void EventUnlockedFeatureUpdated();
	void EventInputSourceChanged();
	void Init_Parent(class UNewMainMenuTest_C* New_Main_Menu_0);
	void EventMenuSpecialLeftPressed();
	void EventMenuRightThumbstick();
	void EventFinalizePrimaryShopTransactionEnd(int32 SpecialPackId, bool transactionSucceeded_0);
	void EventSecondaryShopTransactionEnd(EItemType ItemType, int32 ItemId, bool transactionSucceeded_0);
	void EventFinalizePrimaryShopTransactionBegin();
	void EventSecondaryShopTransactionBegin(EItemType ItemType, int32 ItemId);
	void OnReceivedDuplicateItem();
	void ExecuteUbergraph_CurrencyCount(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CurrencyCount_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CurrencyCount_C")
	}
	static class UCurrencyCount_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurrencyCount_C>();
	}
};
DUMPER7_ASSERTS_UCurrencyCount_C;

SDK_NAMESPACE_END
