#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DarwinEnvironmentNightProfileBP_06

#include "Basic.hpp"

#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DarwinEnvironmentNightProfileBP_06.DarwinEnvironmentNightProfileBP_06_C
// 0x0000 (0x0360 - 0x0360)
class UDarwinEnvironmentNightProfileBP_06_C final : public UDarwinEnvironmentProfile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DarwinEnvironmentNightProfileBP_06_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DarwinEnvironmentNightProfileBP_06_C")
	}
	static class UDarwinEnvironmentNightProfileBP_06_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDarwinEnvironmentNightProfileBP_06_C>();
	}
};
DUMPER7_ASSERTS_UDarwinEnvironmentNightProfileBP_06_C;

SDK_NAMESPACE_END
