#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DarwinTreeClueBP

#include "Basic.hpp"

#include "DarwinTreeClueBP_classes.hpp"
#include "DarwinTreeClueBP_parameters.hpp"


SDK_NAMESPACE_START

// Function DarwinTreeClueBP.DarwinTreeClueBP_C.EventHideOutline
// (Event, Public, BlueprintEvent)

void ADarwinTreeClueBP_C::EventHideOutline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "EventHideOutline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DarwinTreeClueBP.DarwinTreeClueBP_C.EventInitScrapPileClue
// (Event, Public, BlueprintEvent)

void ADarwinTreeClueBP_C::EventInitScrapPileClue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "EventInitScrapPileClue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DarwinTreeClueBP.DarwinTreeClueBP_C.EventShowOutline
// (Event, Public, BlueprintEvent)

void ADarwinTreeClueBP_C::EventShowOutline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "EventShowOutline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DarwinTreeClueBP.DarwinTreeClueBP_C.ExecuteUbergraph_DarwinTreeClueBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADarwinTreeClueBP_C::ExecuteUbergraph_DarwinTreeClueBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "ExecuteUbergraph_DarwinTreeClueBP");

	Params::DarwinTreeClueBP_C_ExecuteUbergraph_DarwinTreeClueBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DarwinTreeClueBP.DarwinTreeClueBP_C.HighlightClue
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    Enable                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   stencil_value                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADarwinTreeClueBP_C::HighlightClue(bool Enable, int32 stencil_value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "HighlightClue");

	Params::DarwinTreeClueBP_C_HighlightClue Parms{};

	Parms.Enable = Enable;
	Parms.stencil_value = stencil_value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DarwinTreeClueBP.DarwinTreeClueBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADarwinTreeClueBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DarwinTreeClueBP.DarwinTreeClueBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADarwinTreeClueBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DarwinTreeClueBP_C", "ReceiveTick");

	Params::DarwinTreeClueBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
