#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DarwinEnvironmentSunsetProfileBP_10

#include "Basic.hpp"

#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DarwinEnvironmentSunsetProfileBP_10.DarwinEnvironmentSunsetProfileBP_10_C
// 0x0000 (0x0360 - 0x0360)
class UDarwinEnvironmentSunsetProfileBP_10_C final : public UDarwinEnvironmentProfile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DarwinEnvironmentSunsetProfileBP_10_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DarwinEnvironmentSunsetProfileBP_10_C")
	}
	static class UDarwinEnvironmentSunsetProfileBP_10_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDarwinEnvironmentSunsetProfileBP_10_C>();
	}
};
DUMPER7_ASSERTS_UDarwinEnvironmentSunsetProfileBP_10_C;

SDK_NAMESPACE_END
