#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DarwinGameStateBP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Darwin_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function DarwinGameStateBP.DarwinGameStateBP_C.CheckChampionChooserBlocked
// 0x0002 (0x0002 - 0x0000)
struct DarwinGameStateBP_C_CheckChampionChooserBlocked final
{
public:
	bool                                          NewParam;                                          // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsTutorial_Tuto;                          // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_DarwinGameStateBP_C_CheckChampionChooserBlocked;

// Function DarwinGameStateBP.DarwinGameStateBP_C.EventExecutePower
// 0x0028 (0x0028 - 0x0000)
struct DarwinGameStateBP_C_EventExecutePower final
{
public:
	class AActor*                                 TargetActor;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Loc;                                               // 0x0008(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDarwinItemTypeEnum                           PowerType;                                         // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bAutoVote;                                         // 0x0021(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_DarwinGameStateBP_C_EventExecutePower;

// Function DarwinGameStateBP.DarwinGameStateBP_C.ExecuteUbergraph_DarwinGameStateBP
// 0x0030 (0x0030 - 0x0000)
struct DarwinGameStateBP_C_ExecuteUbergraph_DarwinGameStateBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_targetActor;                          // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_loc;                                  // 0x0010(0x0018)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDarwinItemTypeEnum                           K2Node_Event_powerType;                            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bAutoVote;                            // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_DarwinGameStateBP_C_ExecuteUbergraph_DarwinGameStateBP;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
