#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DetectorPowerBP

#include "Basic.hpp"

#include "DetectorPowerBP_classes.hpp"
#include "DetectorPowerBP_parameters.hpp"


SDK_NAMESPACE_START

// Function DetectorPowerBP.DetectorPowerBP_C.EventDetectorPulse
// (Event, Public, BlueprintEvent)

void UDetectorPowerBP_C::EventDetectorPulse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DetectorPowerBP_C", "EventDetectorPulse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DetectorPowerBP.DetectorPowerBP_C.ExecuteUbergraph_DetectorPowerBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDetectorPowerBP_C::ExecuteUbergraph_DetectorPowerBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DetectorPowerBP_C", "ExecuteUbergraph_DetectorPowerBP");

	Params::DetectorPowerBP_C_ExecuteUbergraph_DetectorPowerBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
