#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GrapplingHookPowerBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GrapplingHookPowerBP.GrapplingHookPowerBP_C
// 0x0060 (0x01F8 - 0x0198)
class UGrapplingHookPowerBP_C final : public UDarwinGrapplingHookPower
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0198(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               IceBlock;                                          // 0x01A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMap<class UParticleSystemComponent*, class ACharacter*> IceShards;                              // 0x01A8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void EventHookCharacter(class ADarwinCharacter* Character, const struct FVector& Direction);
	void EventUnHookCharacter(class ADarwinCharacter* Character);
	void ExecuteUbergraph_GrapplingHookPowerBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GrapplingHookPowerBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GrapplingHookPowerBP_C")
	}
	static class UGrapplingHookPowerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGrapplingHookPowerBP_C>();
	}
};
DUMPER7_ASSERTS_UGrapplingHookPowerBP_C;

SDK_NAMESPACE_END
