#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MiniMapGameInfo

#include "Basic.hpp"

#include "UMG_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function MiniMapGameInfo.MiniMapGameInfo_C.EventUpdateNumberOfPlayersLeftAlive
// 0x0004 (0x0004 - 0x0000)
struct MiniMapGameInfo_C_EventUpdateNumberOfPlayersLeftAlive final
{
public:
	int32                                         numberAlive;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MiniMapGameInfo_C_EventUpdateNumberOfPlayersLeftAlive;

// Function MiniMapGameInfo.MiniMapGameInfo_C.EventUpdateNumberOfKills
// 0x0004 (0x0004 - 0x0000)
struct MiniMapGameInfo_C_EventUpdateNumberOfKills final
{
public:
	int32                                         nbOfKills;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MiniMapGameInfo_C_EventUpdateNumberOfKills;

// Function MiniMapGameInfo.MiniMapGameInfo_C.ExecuteUbergraph_MiniMapGameInfo
// 0x0058 (0x0058 - 0x0000)
struct MiniMapGameInfo_C_ExecuteUbergraph_MiniMapGameInfo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_numberAlive;                          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0010)()
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0018(0x0010)(HasGetValueTypeHash)
	int32                                         K2Node_Event_nbOfKills;                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_1;              // 0x0030(0x0010)(HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0040(0x0010)()
	bool                                          CallFunc_WithNetease_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MiniMapGameInfo_C_ExecuteUbergraph_MiniMapGameInfo;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
