#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NinjaLootBP

#include "Basic.hpp"

#include "NinjaLootBP_classes.hpp"
#include "NinjaLootBP_parameters.hpp"


SDK_NAMESPACE_START

// Function NinjaLootBP.NinjaLootBP_C.EventLootPickedUp
// (Event, Public, BlueprintEvent)
// Parameters:
// class ADarwinCharacter*                 Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANinjaLootBP_C::EventLootPickedUp(class ADarwinCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NinjaLootBP_C", "EventLootPickedUp");

	Params::NinjaLootBP_C_EventLootPickedUp Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NinjaLootBP.NinjaLootBP_C.EventLootReset
// (Event, Public, BlueprintEvent)

void ANinjaLootBP_C::EventLootReset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NinjaLootBP_C", "EventLootReset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NinjaLootBP.NinjaLootBP_C.ExecuteUbergraph_NinjaLootBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANinjaLootBP_C::ExecuteUbergraph_NinjaLootBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NinjaLootBP_C", "ExecuteUbergraph_NinjaLootBP");

	Params::NinjaLootBP_C_ExecuteUbergraph_NinjaLootBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
