#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NotifLoot_scrap

#include "Basic.hpp"

#include "NotifLoot_scrap_classes.hpp"
#include "NotifLoot_scrap_parameters.hpp"


SDK_NAMESPACE_START

// Function NotifLoot_scrap.NotifLoot_scrap_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UNotifLoot_scrap_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.EventUpdateNumberOfScrap
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   numberOfScrap                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIncrement                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNotifLoot_scrap_C::EventUpdateNumberOfScrap(int32 numberOfScrap, bool bIncrement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "EventUpdateNumberOfScrap");

	Params::NotifLoot_scrap_C_EventUpdateNumberOfScrap Parms{};

	Parms.numberOfScrap = numberOfScrap;
	Parms.bIncrement = bIncrement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.ExecuteUbergraph_NotifLoot_scrap
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNotifLoot_scrap_C::ExecuteUbergraph_NotifLoot_scrap(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "ExecuteUbergraph_NotifLoot_scrap");

	Params::NotifLoot_scrap_C_ExecuteUbergraph_NotifLoot_scrap Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.Initialize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Number_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNotifLoot_scrap_C::Initialize(int32 Number_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "Initialize");

	Params::NotifLoot_scrap_C_Initialize Parms{};

	Parms.Number_0 = Number_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.remove message
// (BlueprintCallable, BlueprintEvent)

void UNotifLoot_scrap_C::remove_message()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "remove message");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNotifLoot_scrap_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "Tick");

	Params::NotifLoot_scrap_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.Update 
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Number_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNotifLoot_scrap_C::Update_(int32 Number_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "Update ");

	Params::NotifLoot_scrap_C_Update_ Parms{};

	Parms.Number_0 = Number_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NotifLoot_scrap.NotifLoot_scrap_C.WidgetAnimationEvt_LootMessageOut_K2Node_WidgetAnimationEvent_0
// (BlueprintEvent)

void UNotifLoot_scrap_C::WidgetAnimationEvt_LootMessageOut_K2Node_WidgetAnimationEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NotifLoot_scrap_C", "WidgetAnimationEvt_LootMessageOut_K2Node_WidgetAnimationEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
