#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NotifTeamElim

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass NotifTeamElim.NotifTeamElim_C
// 0x0018 (0x0758 - 0x0740)
class UNotifTeamElim_C final : public UDarwinUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0740(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             LeaderName;                                        // 0x0748(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       KillAnim;                                          // 0x0750(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_NotifTeamElim(int32 EntryPoint);
	void Initialize(const class FString& LeaderName_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NotifTeamElim_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NotifTeamElim_C")
	}
	static class UNotifTeamElim_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNotifTeamElim_C>();
	}
};
DUMPER7_ASSERTS_UNotifTeamElim_C;

SDK_NAMESPACE_END
