#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerStatusSolo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass PlayerStatusSolo.PlayerStatusSolo_C
// 0x0080 (0x0A18 - 0x0998)
class UPlayerStatusSolo_C final : public UDarwinMainMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0998(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             XPNextSD;                                          // 0x09A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextSDLevel;                                       // 0x09A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SteamAvatar;                                       // 0x09B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_SD;                                    // 0x09B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           PlayerProgressionVB;                               // 0x09C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             PlayerName;                                        // 0x09C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPlayerArchetypeProgression_C*          PlayerArchetypeProgression;                        // 0x09D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Director_Locked;                             // 0x09D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_LvlDirector;                         // 0x09E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_DirectorLevel;                       // 0x09E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_Director_Xp;                         // 0x09F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CurentXPSD;                                        // 0x09F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Show_Director_Level;                               // 0x0A00(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Show_Player_Level;                                 // 0x0A01(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A02[0x6];                                      // 0x0A02(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 AllowedArchetypeIds;                               // 0x0A08(0x0010)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_PlayerStatusSolo(int32 EntryPoint);
	void EventUpdatePlayerName();
	void EventUpdateLocalAvatarTexture(class UTexture* outLocalAvatarTexture_EventUpdateLocalAvatarTexture);
	void EventUpdateAvatarTexture(class UTexture* avatar_EventUpdateAvatarTexture, int32 PlayerID_EventUpdateAvatarTexture);
	void EventPlayerProfileReceived(const class FString& DisplayName_EventPlayerProfileReceived, const struct FDarwinPlayerProgression& PlayerProgression_EventPlayerProfileReceived);
	void Construct();
	void BP_GetHighestArchetypeProgression(const struct FDarwinPlayerProgression& PlayerProgression, struct FDarwinArchetypeProgression* Archetype);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PlayerStatusSolo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerStatusSolo_C")
	}
	static class UPlayerStatusSolo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerStatusSolo_C>();
	}
};
DUMPER7_ASSERTS_UPlayerStatusSolo_C;

SDK_NAMESPACE_END
