#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SalesTab_Boosts

#include "Basic.hpp"

#include "Darwin_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SalesTab_Boosts.SalesTab_Boosts_C.BndEvt__LongItemCard_weekly1_K2Node_ComponentBoundEvent_7_Click on item card__DelegateSignature
// 0x0068 (0x0068 - 0x0000)
struct SalesTab_Boosts_C_BndEvt__LongItemCard_weekly1_K2Node_ComponentBoundEvent_7_Click_on_item_card__DelegateSignature final
{
public:
	class ULongItemCard_C*                        item_card;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    shop_item;                                         // 0x0008(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_BndEvt__LongItemCard_weekly1_K2Node_ComponentBoundEvent_7_Click_on_item_card__DelegateSignature;

// Function SalesTab_Boosts.SalesTab_Boosts_C.BndEvt__LongItemCard_weekly2_K2Node_ComponentBoundEvent_8_Click on item card__DelegateSignature
// 0x0068 (0x0068 - 0x0000)
struct SalesTab_Boosts_C_BndEvt__LongItemCard_weekly2_K2Node_ComponentBoundEvent_8_Click_on_item_card__DelegateSignature final
{
public:
	class ULongItemCard_C*                        item_card;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    shop_item;                                         // 0x0008(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_BndEvt__LongItemCard_weekly2_K2Node_ComponentBoundEvent_8_Click_on_item_card__DelegateSignature;

// Function SalesTab_Boosts.SalesTab_Boosts_C.BndEvt__LongItemCard_weekly3_K2Node_ComponentBoundEvent_9_Click on item card__DelegateSignature
// 0x0068 (0x0068 - 0x0000)
struct SalesTab_Boosts_C_BndEvt__LongItemCard_weekly3_K2Node_ComponentBoundEvent_9_Click_on_item_card__DelegateSignature final
{
public:
	class ULongItemCard_C*                        item_card;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    shop_item;                                         // 0x0008(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_BndEvt__LongItemCard_weekly3_K2Node_ComponentBoundEvent_9_Click_on_item_card__DelegateSignature;

// Function SalesTab_Boosts.SalesTab_Boosts_C.BndEvt__LongItemCard_weekly4_K2Node_ComponentBoundEvent_10_Click on item card__DelegateSignature
// 0x0068 (0x0068 - 0x0000)
struct SalesTab_Boosts_C_BndEvt__LongItemCard_weekly4_K2Node_ComponentBoundEvent_10_Click_on_item_card__DelegateSignature final
{
public:
	class ULongItemCard_C*                        item_card;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    shop_item;                                         // 0x0008(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_BndEvt__LongItemCard_weekly4_K2Node_ComponentBoundEvent_10_Click_on_item_card__DelegateSignature;

// Function SalesTab_Boosts.SalesTab_Boosts_C.BuyCurrentSelection
// 0x0005 (0x0005 - 0x0000)
struct SalesTab_Boosts_C_BuyCurrentSelection final
{
public:
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_1;                  // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_2;                  // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_3;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_BuyCurrentSelection;

// Function SalesTab_Boosts.SalesTab_Boosts_C.EventMenuLeft
// 0x0001 (0x0001 - 0x0000)
struct SalesTab_Boosts_C_EventMenuLeft final
{
public:
	bool                                          bThumbstick;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_EventMenuLeft;

// Function SalesTab_Boosts.SalesTab_Boosts_C.EventMenuRight
// 0x0001 (0x0001 - 0x0000)
struct SalesTab_Boosts_C_EventMenuRight final
{
public:
	bool                                          bThumbstick;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_EventMenuRight;

// Function SalesTab_Boosts.SalesTab_Boosts_C.ExecuteUbergraph_SalesTab_Boosts
// 0x01E8 (0x01E8 - 0x0000)
struct SalesTab_Boosts_C_ExecuteUbergraph_SalesTab_Boosts final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_1;                  // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_2;                  // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetActive_Is_active;                 // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetActive_Is_active_1;               // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess_1;                 // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B[0x5];                                        // 0x000B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ULongItemCard_C*>                K2Node_MakeArray_Array;                            // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_GetIsUsingGamepad_ReturnValue;            // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNewSalesMenu_C*                        K2Node_CustomEvent_Parent;                         // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ULongItemCard_C*                        K2Node_ComponentBoundEvent_item_card_3;            // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    K2Node_ComponentBoundEvent_shop_item_3;            // 0x0038(0x0060)()
	bool                                          CallFunc_IsWidgetActive_Is_active_2;               // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_3;                  // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetActive_Is_active_3;               // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetActive_Is_active_4;               // 0x009B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_4;                  // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetActive_Is_active_5;               // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_5;                  // 0x009E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9F[0x1];                                       // 0x009F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class ULongItemCard_C*                        K2Node_ComponentBoundEvent_item_card_2;            // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    K2Node_ComponentBoundEvent_shop_item_2;            // 0x00A8(0x0060)()
	class ULongItemCard_C*                        K2Node_ComponentBoundEvent_item_card_1;            // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    K2Node_ComponentBoundEvent_shop_item_1;            // 0x0110(0x0060)()
	class ULongItemCard_C*                        K2Node_ComponentBoundEvent_item_card;              // 0x0170(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FDarwinUMGSecondaryShopFeaturedItem    K2Node_ComponentBoundEvent_shop_item;              // 0x0178(0x0060)()
	bool                                          K2Node_Event_bThumbstick_1;                        // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bThumbstick;                          // 0x01D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsWidgetActive_Is_active_6;               // 0x01DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_6;                  // 0x01DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_7;                  // 0x01DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_8;                  // 0x01DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_9;                  // 0x01DE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x01DF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_10;                 // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_11;                 // 0x01E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x01E3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_3;                // 0x01E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01E5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x01E6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x01E7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_ExecuteUbergraph_SalesTab_Boosts;

// Function SalesTab_Boosts.SalesTab_Boosts_C.Init Parent
// 0x0008 (0x0008 - 0x0000)
struct SalesTab_Boosts_C_Init_Parent final
{
public:
	class UNewSalesMenu_C*                        Parent;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_Init_Parent;

// Function SalesTab_Boosts.SalesTab_Boosts_C.IsWidgetActive
// 0x0005 (0x0005 - 0x0000)
struct SalesTab_Boosts_C_IsWidgetActive final
{
public:
	bool                                          Is_active;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsConditionMet_ReturnValue;               // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_IsWidgetActive;

// Function SalesTab_Boosts.SalesTab_Boosts_C.UnselectAllCards
// 0x0020 (0x0020 - 0x0000)
struct SalesTab_Boosts_C_UnselectAllCards final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULongItemCard_C*                        CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_UnselectAllCards;

// Function SalesTab_Boosts.SalesTab_Boosts_C.UpdateCurrentSelection
// 0x0008 (0x0008 - 0x0000)
struct SalesTab_Boosts_C_UpdateCurrentSelection final
{
public:
	int32                                         SelectedCardIndex;                                 // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsUsingGamepad_ReturnValue;            // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SalesTab_Boosts_C_UpdateCurrentSelection;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
