#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextTutoCustomization

#include "Basic.hpp"

#include "Darwin_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass TextTutoCustomization.TextTutoCustomization_C
// 0x0028 (0x0ED0 - 0x0EA8)
class UTextTutoCustomization_C final : public UDarwinCharacterWidget
{
public:
	class UScrollBox*                             ScrollBox_0;                                       // 0x0EA8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_21;                                          // 0x0EB0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_20;                                          // 0x0EB8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_19;                                          // 0x0EC0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0EC8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TextTutoCustomization_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TextTutoCustomization_C")
	}
	static class UTextTutoCustomization_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextTutoCustomization_C>();
	}
};
DUMPER7_ASSERTS_UTextTutoCustomization_C;

SDK_NAMESPACE_END
