#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TripWireBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Darwin_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TripWireBP.TripWireBP_C
// 0x0050 (0x03C0 - 0x0370)
class ATripWireBP_C final : public ADarwinTripwire
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_Explosion_02;                                    // 0x0378(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_Explosion_01;                                    // 0x0380(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          AxeCol;                                            // 0x0388(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           AkTripwire;                                        // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          PickupShape;                                       // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   FadeMesh;                                          // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void DisableAllCollisions();
	void EventCraftableToolDestroyed(const struct FVector& Loc);
	void EventCraftableToolDestroyedDedicatedServer(const struct FVector& Loc);
	void EventCraftableToolSprung(class ADarwinCharacter* characterTarget);
	void EventCraftableToolSprungDedicatedServer(class ADarwinCharacter* characterTarget);
	void EventInitializeMeshArray();
	void ExecuteUbergraph_TripWireBP(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TripWireBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TripWireBP_C")
	}
	static class ATripWireBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATripWireBP_C>();
	}
};
DUMPER7_ASSERTS_ATripWireBP_C;

SDK_NAMESPACE_END
