#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VersusAi_Difficulty

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Darwin_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.BndEvt__ChooseMenus_Cards_Easy_K2Node_ComponentBoundEvent_3_On click__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct VersusAi_Difficulty_C_BndEvt__ChooseMenus_Cards_Easy_K2Node_ComponentBoundEvent_3_On_click__DelegateSignature final
{
public:
	struct FDarwinFeaturedMatchmakingQueue        FeaturedQueue;                                     // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_BndEvt__ChooseMenus_Cards_Easy_K2Node_ComponentBoundEvent_3_On_click__DelegateSignature;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.BndEvt__ChooseMenus_Cards_HARD_K2Node_ComponentBoundEvent_5_On click__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct VersusAi_Difficulty_C_BndEvt__ChooseMenus_Cards_HARD_K2Node_ComponentBoundEvent_5_On_click__DelegateSignature final
{
public:
	struct FDarwinFeaturedMatchmakingQueue        FeaturedQueue;                                     // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_BndEvt__ChooseMenus_Cards_HARD_K2Node_ComponentBoundEvent_5_On_click__DelegateSignature;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.BndEvt__ChooseMenus_Cards_Medium_K2Node_ComponentBoundEvent_4_On click__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct VersusAi_Difficulty_C_BndEvt__ChooseMenus_Cards_Medium_K2Node_ComponentBoundEvent_4_On_click__DelegateSignature final
{
public:
	struct FDarwinFeaturedMatchmakingQueue        FeaturedQueue;                                     // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_BndEvt__ChooseMenus_Cards_Medium_K2Node_ComponentBoundEvent_4_On_click__DelegateSignature;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.EventMenuLeft
// 0x0001 (0x0001 - 0x0000)
struct VersusAi_Difficulty_C_EventMenuLeft final
{
public:
	bool                                          bThumbstick;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_EventMenuLeft;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.EventMenuRight
// 0x0001 (0x0001 - 0x0000)
struct VersusAi_Difficulty_C_EventMenuRight final
{
public:
	bool                                          bThumbstick;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_EventMenuRight;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.ExecuteUbergraph_VersusAi_Difficulty
// 0x0100 (0x0100 - 0x0000)
struct VersusAi_Difficulty_C_ExecuteUbergraph_VersusAi_Difficulty final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0010)(HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue_1;              // 0x0018(0x0010)(HasGetValueTypeHash)
	struct FDarwinFeaturedMatchmakingQueue        K2Node_ComponentBoundEvent_FeaturedQueue_2;        // 0x0028(0x0030)()
	bool                                          CallFunc_GetIsUsingGamepad_ReturnValue;            // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UChooseMenus_Cards_C*>           K2Node_MakeArray_Array;                            // 0x0060(0x0010)(ReferenceParm, ContainsInstancedReference)
	struct FDarwinFeaturedMatchmakingQueue        K2Node_ComponentBoundEvent_FeaturedQueue_1;        // 0x0070(0x0030)()
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue_1;                  // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bThumbstick_1;                        // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bThumbstick;                          // 0x00A3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess_1;                 // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Is_menu_visible_Visible;                  // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Is_menu_visible_Visible_1;                // 0x00A7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FDarwinFeaturedMatchmakingQueue        K2Node_ComponentBoundEvent_FeaturedQueue;          // 0x00A8(0x0030)()
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMediumAIDifficultyLocked_ReturnValue;   // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMediumAIDifficultyLocked_ReturnValue_1; // 0x00FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_ExecuteUbergraph_VersusAi_Difficulty;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.Is menu visible
// 0x0002 (0x0002 - 0x0000)
struct VersusAi_Difficulty_C_Is_menu_visible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_Is_menu_visible;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct VersusAi_Difficulty_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_PreConstruct;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.select card
// 0x0018 (0x0018 - 0x0000)
struct VersusAi_Difficulty_C_select_card final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UChooseMenus_Cards_C*                   CallFunc_Array_Get_Item;                           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_select_card;

// Function VersusAi_Difficulty.VersusAi_Difficulty_C.Unselect Current card
// 0x0010 (0x0010 - 0x0000)
struct VersusAi_Difficulty_C_Unselect_Current_card final
{
public:
	class UChooseMenus_Cards_C*                   CallFunc_Array_Get_Item;                           // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_VersusAi_Difficulty_C_Unselect_Current_card;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
